/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juegoQuoridor.GUI;

import jade.content.ContentManager;
import java.awt.ComponentOrientation;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import juegoQuoridor.elementos.Movimiento;
import juegoQuoridor.elementos.MovimientoRealizado;
import juegoQuoridor.elementos.Muro;
import juegoQuoridor.utils.Casilla;
import juegoQuoridor.utils.RepresentacionMovimiento;
import juegosTablero.elementos.Ficha;
import juegosTablero.elementos.Jugador;
import juegosTablero.elementos.Posicion;

/**
 *
 * @author hacker
 */
public class GUI extends javax.swing.JFrame {
    //private final AgenteTablero myAgent;

    JLabel labels[][] = new JLabel[17][17];
    GridBagLayout grid;
    ContentManager manager;

    /**
     * Creates new form GUI
     */
    public GUI(ContentManager _manager) {
        grid = new GridBagLayout();
        initComponents();
        addComponentsToPane();
        add(panelTablero);
        
        panelJugador1.setEnabled(false);
        panelJugador2.setEnabled(false);
        panelJugador3.setEnabled(false);
        panelJugador4.setEnabled(false);
        manager = _manager;
    }

    public void addComponentsToPane() {

        panelTablero.setComponentOrientation(ComponentOrientation.LEFT_TO_RIGHT);
        panelTablero.setLayout(grid);

        GridBagConstraints c = new GridBagConstraints();
        String path = "tablero.png";
        URL url = this.getClass().getResource(path);
        ImageIcon casilla = new ImageIcon(url);

        path = "separacion-vertical.png";
        url = this.getClass().getResource(path);
        ImageIcon separacionV = new ImageIcon(url);

        path = "separacion-horizontal.png";
        url = this.getClass().getResource(path);
        ImageIcon separacionH = new ImageIcon(url);

        for (int i = 0; i < 17; i++) {
            if (i % 2 != 0) {
                for (int j = 0; j < 17; j++) {
                    JLabel label;
                    if (j % 2 == 0) {
                        label = new JLabel(separacionV);
                        label.setText("");
                    } else {
                        label = new JLabel();
                        label.setText("");
                    }
                    labels[i][j] = label;
                    //labels[i][j].setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                    c.fill = GridBagConstraints.HORIZONTAL;
                    c.gridx = i;
                    c.gridy = j;
                    panelTablero.add(labels[i][j], c);
                }
            } else {
                for (int j = 0; j < 17; j++) {
                    JLabel label;
                    if (j % 2 == 0) {
                        label = new JLabel(casilla);
                    } else {
                        label = new JLabel(separacionH);
                    }
                    labels[i][j] = label;
                    //labels[i][j].setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                    c.fill = GridBagConstraints.HORIZONTAL;
                    c.gridx = i;
                    c.gridy = j;
                    panelTablero.add(labels[i][j], c);
                }
            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTablero = new javax.swing.JPanel();
        infoJugadores = new javax.swing.JPanel();
        panelJugador1 = new javax.swing.JPanel();
        imgJugador1 = new javax.swing.JLabel();
        nombreJugador1 = new javax.swing.JLabel();
        murosJugador1 = new javax.swing.JLabel();
        panelJugador2 = new javax.swing.JPanel();
        nombreJugador2 = new javax.swing.JLabel();
        murosJugador2 = new javax.swing.JLabel();
        imgJugador2 = new javax.swing.JLabel();
        panelJugador3 = new javax.swing.JPanel();
        nombreJugador3 = new javax.swing.JLabel();
        murosJugador3 = new javax.swing.JLabel();
        imgJugador3 = new javax.swing.JLabel();
        panelJugador4 = new javax.swing.JPanel();
        nombreJugador4 = new javax.swing.JLabel();
        murosJugador4 = new javax.swing.JLabel();
        imgJugador4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(610, 650));
        setMinimumSize(new java.awt.Dimension(610, 650));
        setPreferredSize(new java.awt.Dimension(610, 650));
        setResizable(false);

        panelTablero.setMaximumSize(new java.awt.Dimension(450, 450));
        panelTablero.setMinimumSize(new java.awt.Dimension(450, 450));
        panelTablero.setName(""); // NOI18N
        panelTablero.setPreferredSize(new java.awt.Dimension(450, 450));

        javax.swing.GroupLayout panelTableroLayout = new javax.swing.GroupLayout(panelTablero);
        panelTablero.setLayout(panelTableroLayout);
        panelTableroLayout.setHorizontalGroup(
            panelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        panelTableroLayout.setVerticalGroup(
            panelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        infoJugadores.setMaximumSize(new java.awt.Dimension(450, 135));
        infoJugadores.setMinimumSize(new java.awt.Dimension(450, 135));

        panelJugador1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelJugador1.setPreferredSize(new java.awt.Dimension(118, 113));

        imgJugador1.setMaximumSize(new java.awt.Dimension(40, 40));
        imgJugador1.setMinimumSize(new java.awt.Dimension(40, 40));
        imgJugador1.setPreferredSize(new java.awt.Dimension(40, 40));

        nombreJugador1.setText("jLabel1");

        murosJugador1.setText("Muros: 10");

        javax.swing.GroupLayout panelJugador1Layout = new javax.swing.GroupLayout(panelJugador1);
        panelJugador1.setLayout(panelJugador1Layout);
        panelJugador1Layout.setHorizontalGroup(
            panelJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJugador1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreJugador1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelJugador1Layout.createSequentialGroup()
                        .addComponent(murosJugador1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelJugador1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(imgJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        panelJugador1Layout.setVerticalGroup(
            panelJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJugador1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nombreJugador1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(murosJugador1)
                .addGap(24, 24, 24))
        );

        panelJugador2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nombreJugador2.setText("jLabel1");

        murosJugador2.setText("Muros: 10");

        imgJugador2.setMaximumSize(new java.awt.Dimension(40, 40));
        imgJugador2.setMinimumSize(new java.awt.Dimension(40, 40));
        imgJugador2.setPreferredSize(new java.awt.Dimension(40, 40));

        javax.swing.GroupLayout panelJugador2Layout = new javax.swing.GroupLayout(panelJugador2);
        panelJugador2.setLayout(panelJugador2Layout);
        panelJugador2Layout.setHorizontalGroup(
            panelJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJugador2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreJugador2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelJugador2Layout.createSequentialGroup()
                        .addComponent(murosJugador2)
                        .addGap(0, 70, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelJugador2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(imgJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelJugador2Layout.setVerticalGroup(
            panelJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJugador2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nombreJugador2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(murosJugador2)
                .addGap(24, 24, 24))
        );

        panelJugador3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelJugador3.setPreferredSize(new java.awt.Dimension(118, 113));

        nombreJugador3.setText("Inactivo");

        murosJugador3.setText("Muros: 10");

        imgJugador3.setMaximumSize(new java.awt.Dimension(40, 40));
        imgJugador3.setMinimumSize(new java.awt.Dimension(40, 40));
        imgJugador3.setPreferredSize(new java.awt.Dimension(40, 40));

        javax.swing.GroupLayout panelJugador3Layout = new javax.swing.GroupLayout(panelJugador3);
        panelJugador3.setLayout(panelJugador3Layout);
        panelJugador3Layout.setHorizontalGroup(
            panelJugador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJugador3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelJugador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreJugador3, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addGroup(panelJugador3Layout.createSequentialGroup()
                        .addComponent(murosJugador3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelJugador3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(imgJugador3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelJugador3Layout.setVerticalGroup(
            panelJugador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJugador3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgJugador3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(nombreJugador3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(murosJugador3)
                .addGap(24, 24, 24))
        );

        panelJugador4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelJugador4.setPreferredSize(new java.awt.Dimension(118, 113));

        nombreJugador4.setText("Inactivo");

        murosJugador4.setText("Muros: 10");

        imgJugador4.setMaximumSize(new java.awt.Dimension(40, 40));
        imgJugador4.setMinimumSize(new java.awt.Dimension(40, 40));
        imgJugador4.setPreferredSize(new java.awt.Dimension(40, 40));

        javax.swing.GroupLayout panelJugador4Layout = new javax.swing.GroupLayout(panelJugador4);
        panelJugador4.setLayout(panelJugador4Layout);
        panelJugador4Layout.setHorizontalGroup(
            panelJugador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJugador4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelJugador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreJugador4, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addGroup(panelJugador4Layout.createSequentialGroup()
                        .addComponent(murosJugador4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelJugador4Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(imgJugador4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelJugador4Layout.setVerticalGroup(
            panelJugador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJugador4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgJugador4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(nombreJugador4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(murosJugador4)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout infoJugadoresLayout = new javax.swing.GroupLayout(infoJugadores);
        infoJugadores.setLayout(infoJugadoresLayout);
        infoJugadoresLayout.setHorizontalGroup(
            infoJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoJugadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(panelJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelJugador3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelJugador4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        infoJugadoresLayout.setVerticalGroup(
            infoJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoJugadoresLayout.createSequentialGroup()
                .addGroup(infoJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelJugador1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(panelJugador2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(panelJugador3, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(panelJugador4, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infoJugadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(infoJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GUI().setVisible(true);
//            }
//        });
//    }
    public void representarMovimiento(MovimientoRealizado _m, Casilla _posAnterior) {
        try {
            Movimiento mov = _m.getMovimiento();
            Jugador jugador = _m.getJugador();
            Ficha ficha = jugador.getFicha();
            Posicion pos = mov.getPosicion();
            Object elementoJuego = mov.getElementoJuego();

            if (elementoJuego instanceof Muro) {
                if (elementoJuego != null) {
                    if (((Muro) (elementoJuego)).getAlineacion().equals(juegoQuoridor.OntologiaQuoridor.ALINEACION_HORIZONTAL)) {
                        String path = "muro-horizontal.png";
                        URL url = this.getClass().getResource(path);
                        ImageIcon muro = new ImageIcon(url);
                        labels[pos.getCoorX() * 2][(pos.getCoorY() * 2) + 1].setIcon(muro);
                        labels[(pos.getCoorX() * 2) + 2][(pos.getCoorY() * 2) + 1].setIcon(muro);
                    } else {
                        //Vertical
                        String path = "muro-vertical.png";
                        URL url = this.getClass().getResource(path);
                        ImageIcon muro = new ImageIcon(url);
                        labels[(pos.getCoorX() * 2) + 1][(pos.getCoorY() * 2)].setIcon(muro);
                        labels[(pos.getCoorX() * 2) + 1][(pos.getCoorY() * 2) + 2].setIcon(muro);
                    }
                }
            } else {//Es una Ficha
                URL url = null;
                String path = null;
                switch (ficha.getColor()) {
                    case juegoQuoridor.OntologiaQuoridor.COLOR_FICHA_1:
                        path = "casilla-ficha-rojo.png";
                        break;
                    case juegoQuoridor.OntologiaQuoridor.COLOR_FICHA_2:
                        path = "casilla-ficha-azul.png";
                        break;
                    case juegoQuoridor.OntologiaQuoridor.COLOR_FICHA_3:
                        path = "casilla-ficha-verde.png";
                        break;
                    case juegoQuoridor.OntologiaQuoridor.COLOR_FICHA_4:
                        path = "casilla-ficha-negro.png";
                        break;
                    default:
                        break;
                }
                url = this.getClass().getResource(path);
                ImageIcon imgFicha = new ImageIcon(url);
                labels[pos.getCoorX() * 2][pos.getCoorY() * 2].setIcon(imgFicha);

                //Cambio la imagen de la posicion anterior que tenia la ficha por una vacia
                path = "tablero.png";
                url = this.getClass().getResource(path);
                ImageIcon casilla = new ImageIcon(url);
                labels[_posAnterior.getX() * 2][_posAnterior.getY() * 2].setIcon(casilla);
                System.out.println("He cambiado de posicion");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void cargaFichas(ArrayList<Casilla> _c) {
        URL url;
        String path = null;
        String path2=null;
        ImageIcon imgFicha;
        for(Casilla c:_c){
            switch (c.getJugador().getFicha().getColor()) {
                case juegoQuoridor.OntologiaQuoridor.COLOR_FICHA_1:
                    path = "casilla-ficha-rojo.png";
                    path2 = "ficha-rojo.png";
                    url=this.getClass().getResource(path2);
                    imgFicha = new ImageIcon(url);
                    panelJugador1.setEnabled(true);
                    imgJugador1.setIcon(imgFicha);
                    nombreJugador1.setText(c.getJugador().getAgenteJugador().getName());
                    murosJugador1.setText("Muros: 10");
                    break;
                case juegoQuoridor.OntologiaQuoridor.COLOR_FICHA_2:
                    path = "casilla-ficha-azul.png";
                    path2 = "ficha-azul.png";
                    url=this.getClass().getResource(path2);
                    imgFicha = new ImageIcon(url);
                    panelJugador2.setEnabled(true);
                    imgJugador2.setIcon(imgFicha);
                    nombreJugador2.setText(c.getJugador().getAgenteJugador().getName());
                    murosJugador2.setText("Muros: 10");
                    break;
                case juegoQuoridor.OntologiaQuoridor.COLOR_FICHA_3:
                    path = "casilla-ficha-verde.png";
                    path2 = "ficha-verde.png";
                    url=this.getClass().getResource(path2);
                    imgFicha = new ImageIcon(url);
                    panelJugador3.setEnabled(true);
                    imgJugador3.setIcon(imgFicha);
                    nombreJugador3.setText(c.getJugador().getAgenteJugador().getName());
                    murosJugador3.setText("Muros: 10");
                    break;
                case juegoQuoridor.OntologiaQuoridor.COLOR_FICHA_4:
                    path = "casilla-ficha-negro.png";
                    path2 = "ficha-negro.png";
                    url=this.getClass().getResource(path2);
                    imgFicha = new ImageIcon(url);
                    panelJugador4.setEnabled(true);
                    imgJugador4.setIcon(imgFicha);
                    nombreJugador3.setText(c.getJugador().getAgenteJugador().getName());
                    murosJugador3.setText("Muros: 10");
                    break;
                default:
                    break;
            }
            
            url = this.getClass().getResource(path);
            imgFicha = new ImageIcon(url);
            labels[c.getX()*2][c.getY()*2].setIcon(imgFicha);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgJugador1;
    private javax.swing.JLabel imgJugador2;
    private javax.swing.JLabel imgJugador3;
    private javax.swing.JLabel imgJugador4;
    private javax.swing.JPanel infoJugadores;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel murosJugador1;
    private javax.swing.JLabel murosJugador2;
    private javax.swing.JLabel murosJugador3;
    private javax.swing.JLabel murosJugador4;
    private javax.swing.JLabel nombreJugador1;
    private javax.swing.JLabel nombreJugador2;
    private javax.swing.JLabel nombreJugador3;
    private javax.swing.JLabel nombreJugador4;
    private javax.swing.JPanel panelJugador1;
    private javax.swing.JPanel panelJugador2;
    private javax.swing.JPanel panelJugador3;
    private javax.swing.JPanel panelJugador4;
    private javax.swing.JPanel panelTablero;
    // End of variables declaration//GEN-END:variables

}
